# type: ignore
"""AST recognition, validation, and auto-wrap lowering for ``qd.checkpoint(...)`` ``with`` blocks.

Lives alongside ``call_transformer.py`` / ``function_def_transformer.py`` so that ``ast_transformer.py`` doesn't have to
grow per-feature. ``ASTTransformer.build_With`` and ``ASTTransformer._is_checkpoint_call`` forward calls into the static
methods here. ``FunctionDefTransformer.build_FunctionDef`` calls ``auto_wrap_for_loops`` on the kernel body when the
kernel was decorated with ``@qd.kernel(graph=True, checkpoints=True)``, so that every top-level for-loop not already
inside a ``with qd.checkpoint(...)`` becomes its own implicit no-yield checkpoint.

See ``docs/source/user_guide/graph.md`` for the user-facing surface and ``perso_hugh/doc/qipc/reentrant.md`` for the
design.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass

from quadrants.lang.ast.ast_transformer_utils import ASTTransformerFuncContext
from quadrants.lang.exception import QuadrantsSyntaxError

# Sentinel name used by `_kernel_coverage.py` (`FIELD_VAR_NAME`) for the probe-tracking field. The checkpoint validator
# hard-codes the literal so coverage probes can be exempted from the bare-statement check without taking a runtime dep
# on the optional `_kernel_coverage` module (it is only imported when `QD_KERNEL_COVERAGE=1`). The two must stay in
# sync; if `FIELD_VAR_NAME` ever changes, update this constant and the corresponding test.
_KERNEL_COVERAGE_FIELD_NAME = "_qd_cov"

# Attribute name attached to synthetic `qd.checkpoint()` AST Call nodes generated by `auto_wrap_for_loops` for the
# implicit-no-yield wrap of top-level for-loops in a `checkpoints=True` kernel. Distinguishes auto-wrap calls from
# user-written `qd.checkpoint(cp_id, yield_on)` calls so the validator can apply different rules (implicit calls take no
# args; explicit calls require both `cp_id` and `yield_on`).
_IMPLICIT_MARKER_ATTR = "_qd_implicit"


@dataclass
class CheckpointCallInfo:
    """Resolved metadata for a `qd.checkpoint(...)` call recognised in the AST.

    - ``cp_id``: the user-supplied label (an ``int`` or ``IntEnum`` value), or ``None`` for an auto-wrap implicit
      checkpoint.
    - ``yield_on_node``: the ``ast.expr`` passed as ``yield_on=`` -- either an ``ast.Name`` (bare kernel parameter, e.g.
      ``flag``) or an ``ast.Attribute`` chain (e.g. ``self.flag`` for a ``@qd.data_oriented`` owner, or ``params.flag``
      where ``params`` is a ``@dataclasses.dataclass`` kernel parameter). ``None`` for an implicit checkpoint.
      ``build_checkpoint_with`` resolves the node to a flat C++ arg-id via
      ``ASTTransformer._resolve_ndarray_kernel_arg_id`` so the runtime can forward it directly without per-launch name
      matching.
    - ``is_implicit``: ``True`` iff this Call was synthesised by ``auto_wrap_for_loops``.
    """

    cp_id: int | None
    yield_on_node: ast.expr | None
    is_implicit: bool


class CheckpointTransformer:
    @staticmethod
    def _is_coverage_probe_assign(stmt: ast.stmt) -> bool:
        """Return True iff *stmt* is the synthesized ``_qd_cov[<probe_id>] = 1`` assignment inserted by
        ``_kernel_coverage.py`` when ``QD_KERNEL_COVERAGE=1``. Keeping these out of the bare-statement rejection in
        ``build_checkpoint_with`` lets coverage CI exercise every checkpoint kernel without the user having to wrap the
        synthetic probes themselves.
        """
        if not isinstance(stmt, ast.Assign) or len(stmt.targets) != 1:
            return False
        tgt = stmt.targets[0]
        if not isinstance(tgt, ast.Subscript):
            return False
        return isinstance(tgt.value, ast.Name) and tgt.value.id == _KERNEL_COVERAGE_FIELD_NAME

    @staticmethod
    def _looks_like_checkpoint_call(node: ast.expr) -> bool:
        """Cheap structural check: is *node* `qd.checkpoint(...)` or bare `checkpoint(...)`? Doesn't validate args or
        resolve names; used by ``auto_wrap_for_loops`` to skip already-wrapped `with` blocks without paying for the full
        argument-resolution pass (which needs ``global_vars`` and a real Kernel object)."""
        if not isinstance(node, ast.Call):
            return False
        func = node.func
        return (isinstance(func, ast.Attribute) and func.attr == "checkpoint") or (
            isinstance(func, ast.Name) and func.id == "checkpoint"
        )

    @staticmethod
    def is_explicit_checkpoint_with(stmt: ast.stmt) -> bool:
        """Return True iff *stmt* is a single-item `with qd.checkpoint(...):` block (explicit or implicit). Used by
        ``auto_wrap_for_loops`` to leave already-wrapped for-loops alone."""
        if not isinstance(stmt, ast.With) or len(stmt.items) != 1:
            return False
        return CheckpointTransformer._looks_like_checkpoint_call(stmt.items[0].context_expr)

    @staticmethod
    def _resolve_cp_id(node: ast.expr, global_vars: dict) -> int:
        """Resolve the first positional arg of `qd.checkpoint(cp_id, ...)` to a Python int (or IntEnum instance).

        Accepts (a) `ast.Constant` int literals (``qd.checkpoint(0, ...)``), (b) `ast.Attribute` references to `IntEnum`
        values resolved against the kernel's `global_vars` (``qd.checkpoint(Stage.SIM, ...)`` where ``Stage`` is an
        `IntEnum` defined at module scope), and (c) `ast.Name` references to module-level int constants
        (``qd.checkpoint(CP_LOAD, ...)`` where ``CP_LOAD`` is an int defined at module scope). For (b) and (c) we return
        the resolved value AS-IS (without re-wrapping through `int(...)`) so an IntEnum member identity is preserved
        end-to-end -- the user writes `qd.checkpoint(Stage.SIM, ...)`, then reads `status.checkpoint` and gets back
        `Stage.SIM`, not the raw int. Rejects everything else with a clear error so the user gets a compile-time
        diagnostic rather than a confusing template-mapper failure later.
        """
        # Plain `qd.checkpoint(0, ...)` literal.
        if isinstance(node, ast.Constant) and isinstance(node.value, int) and not isinstance(node.value, bool):
            return node.value
        # `qd.checkpoint(Stage.SIM, ...)` -- look up `Stage` in the kernel's module globals, then `.SIM` on it.
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
            container_name = node.value.id
            if container_name in global_vars:
                container = global_vars[container_name]
                if hasattr(container, node.attr):
                    val = getattr(container, node.attr)
                    if isinstance(val, int) and not isinstance(val, bool):
                        return val
        # `qd.checkpoint(CP_LOAD, ...)` -- bare name referencing a module-level int constant.
        if isinstance(node, ast.Name) and node.id in global_vars:
            val = global_vars[node.id]
            if isinstance(val, int) and not isinstance(val, bool):
                return val
        raise QuadrantsSyntaxError(
            "qd.checkpoint() first argument must be an int literal or an IntEnum value (e.g. `Stage.SIM`). Got an "
            f"unresolvable expression at line {getattr(node, 'lineno', '?')}; the cp_id must be statically "
            "determinable at AST-walk time so the framework can build the label -> internal cp_id map and the "
            "host-side resume API can refer to checkpoints by name."
        )

    @staticmethod
    def is_checkpoint_call(node: ast.expr, global_vars: dict) -> CheckpointCallInfo | None:
        """If *node* is a `qd.checkpoint(...)` call return a `CheckpointCallInfo`; otherwise return `None`.

        Validates the call shape and raises `QuadrantsSyntaxError` for misuse so the user gets a clear message at the
        `with` site rather than a vague "not stream_parallel" error later. Implicit calls (the synthetic
        `qd.checkpoint()` no-arg calls produced by `auto_wrap_for_loops`) are recognised via the `_qd_implicit`
        attribute and bypass user-call argument validation entirely.
        """
        if not CheckpointTransformer._looks_like_checkpoint_call(node):
            return None
        # Auto-wrap-synthesised implicit checkpoint: no user-facing args, no validation.
        if getattr(node, _IMPLICIT_MARKER_ATTR, False):
            return CheckpointCallInfo(cp_id=None, yield_on_node=None, is_implicit=True)
        # User-written `qd.checkpoint(cp_id, yield_on)` -- both args are required.
        if len(node.args) + len(node.keywords) == 0:
            raise QuadrantsSyntaxError("qd.checkpoint() takes two arguments: `qd.checkpoint(cp_id, yield_on=flag)`.")
        # Collect cp_id (positional 0 or kw `cp_id=`) and yield_on (positional 1 or kw `yield_on=`).
        cp_id_arg: ast.expr | None = None
        yield_on_arg: ast.expr | None = None
        for i, arg in enumerate(node.args):
            if i == 0:
                cp_id_arg = arg
            elif i == 1:
                yield_on_arg = arg
            else:
                raise QuadrantsSyntaxError(
                    f"qd.checkpoint() takes at most 2 positional arguments (cp_id, yield_on); got {len(node.args)}"
                )
        for kw in node.keywords:
            if kw.arg == "cp_id":
                if cp_id_arg is not None:
                    raise QuadrantsSyntaxError("qd.checkpoint() got `cp_id` both positionally and as a keyword")
                cp_id_arg = kw.value
            elif kw.arg == "yield_on":
                if yield_on_arg is not None:
                    raise QuadrantsSyntaxError("qd.checkpoint() got `yield_on` both positionally and as a keyword")
                yield_on_arg = kw.value
            else:
                raise QuadrantsSyntaxError(
                    f"qd.checkpoint() got unexpected keyword argument {kw.arg!r}; only 'cp_id' and 'yield_on' are "
                    "supported"
                )
        if cp_id_arg is None:
            raise QuadrantsSyntaxError(
                "qd.checkpoint() is missing required argument `cp_id` (e.g. `qd.checkpoint(0, yield_on=flag)` or "
                "`qd.checkpoint(Stage.SIM, yield_on=flag)`)"
            )
        if yield_on_arg is None:
            raise QuadrantsSyntaxError(
                "qd.checkpoint() is missing required argument `yield_on` (e.g. "
                "`qd.checkpoint(0, yield_on=overflow_flag)`)"
            )
        # `yield_on=` must point at an ndarray kernel argument -- a bare parameter (`yield_on=flag`), a
        # `@qd.data_oriented` member (`yield_on=self.flag`), or a `@dataclasses.dataclass` parameter member
        # (`yield_on=params.flag`). Other expressions can't be lowered to a flat arg-id and are rejected here so the
        # user gets a clear compile-time error at the `with` site.
        if not isinstance(yield_on_arg, (ast.Name, ast.Attribute)):
            raise QuadrantsSyntaxError(
                "qd.checkpoint(yield_on=...) must reference a kernel ndarray argument -- e.g. `yield_on=flag` for "
                "a bare parameter, `yield_on=self.flag` for a @qd.data_oriented member, or `yield_on=params.flag` "
                "for a @dataclasses.dataclass parameter member; arbitrary expressions are not supported"
            )
        cp_id_value = CheckpointTransformer._resolve_cp_id(cp_id_arg, global_vars)
        return CheckpointCallInfo(cp_id=cp_id_value, yield_on_node=yield_on_arg, is_implicit=False)

    @staticmethod
    def build_checkpoint_with(
        ctx: ASTTransformerFuncContext,
        node: ast.With,
        info: CheckpointCallInfo,
        build_stmts,
    ) -> None:
        """Handles a `with qd.checkpoint(...):` block (explicit or auto-wrapped implicit).

        Validates the use-site (kernel must be `graph=True, checkpoints=True`, no nesting; for explicit calls, the
        `yield_on` arg must be a kernel parameter and the `cp_id` must be unique across the kernel) and appends an entry
        to `kernel.checkpoint_yield_on_args` + `kernel.checkpoint_user_labels_by_cp_id`. Walks the body transparently --
        for-loops inside the `with` become normal top-level for-loops in the kernel's frontend IR. The internal `cp_id`
        is assigned by declaration order (the C++ `ASTBuilder.begin_checkpoint()` counter, mirrored as the list index in
        `checkpoint_yield_on_args`).
        """
        if not ctx.is_kernel:
            raise QuadrantsSyntaxError("qd.checkpoint() can only be used inside @qd.kernel, not @qd.func")
        kernel = ctx.global_context.current_kernel
        if not kernel.use_graph:
            raise QuadrantsSyntaxError(
                "qd.checkpoint() requires @qd.kernel(graph=True); the resume model only applies to graph kernels"
            )
        if not kernel.use_checkpoints:
            raise QuadrantsSyntaxError(
                f"qd.checkpoint() found in kernel {kernel.func.__name__!r}, but this kernel was not decorated with "
                "`checkpoints=True`. Add `checkpoints=True` to the decorator -- e.g. "
                "`@qd.kernel(graph=True, checkpoints=True)` -- to opt into the pause / resume model."
            )
        if getattr(ctx, "_in_checkpoint", False):
            raise QuadrantsSyntaxError(
                "qd.checkpoint() cannot be nested inside another qd.checkpoint(); checkpoints in the "
                "same kernel must be flat siblings (a checkpoint inside qd.graph.do_while is fine)"
            )

        yield_on_label: str | None = None
        yield_on_cpp_arg_id: int = -1
        if not info.is_implicit:
            # Resolve `yield_on=` (a bare parameter or `@qd.data_oriented` / `@dataclasses.dataclass` member ndarray) to
            # its flat C++ arg-id at AST-build time. ``resolve_ndarray_kernel_arg_id`` raises a user-facing
            # ``QuadrantsSyntaxError`` if the expression does not name a real ndarray kernel argument, which keeps the
            # diagnostic at the `with` site instead of leaking into the launcher. Both the label (for
            # ``checkpoint_yield_on_args`` / introspection) and the resolved arg-id (for the runtime) are stashed and
            # forwarded to the launch path below.
            # pylint: disable-next=C0415,import-outside-toplevel
            from quadrants.lang.ast.ast_transformers.ndarray_arg_resolver import (
                resolve_ndarray_kernel_arg_id,
            )

            yield_on_label, yield_on_cpp_arg_id = resolve_ndarray_kernel_arg_id(
                ctx, kernel, info.yield_on_node, "qd.checkpoint(yield_on=...)"
            )
            # Reject duplicate user-supplied cp_id labels.
            existing = [lbl for lbl in kernel.checkpoint_user_labels_by_cp_id if lbl is not None]
            if info.cp_id in existing:
                raise QuadrantsSyntaxError(
                    f"qd.checkpoint(cp_id={info.cp_id!r}, ...) declares a cp_id that is already used by another "
                    f"checkpoint in kernel {kernel.func.__name__!r}. Each `cp_id` label must be unique so the host "
                    "loop can map `status.checkpoint` and `kernel.resume(from_checkpoint=...)` unambiguously."
                )

        # Reject bare top-level statements (Assign / AugAssign / AnnAssign / non-docstring Expr) at the top of the
        # checkpoint body and ask the user to wrap them in their own for-loop. The offloader's pending-serial bucket
        # loses the surrounding `checkpoint_id` and emits such statements as `serial` tasks with `cp_id == -1`, so they
        # would run unconditionally even when the checkpoint is skipped -- a silent correctness bug. Rather than
        # auto-wrapping them transparently (which hides the fact that each bare stmt becomes its own kernel / graph node
        # and surprises users when they look at the lowered IR or `prog.get_num_offloaded_tasks_on_last_call()`), we
        # surface a clear compile-time error and have the user write `for _ in range(1): <stmt>` themselves. Implicit
        # (auto-wrapped) checkpoints can never trip this -- they wrap exactly one ast.For. Coverage probes (synthesized
        # `_qd_cov[i] = 1` assignments under `QD_KERNEL_COVERAGE=1`) are explicitly exempt; the cp_id propagation in
        # `quadrants/transforms/offload.cpp` (`assemble_serial_statements`) makes them inherit the surrounding
        # checkpoint's cp_id so the launcher's "last task in checkpoint" detection stays correct.
        for stmt in node.body:
            is_bare = isinstance(stmt, (ast.Assign, ast.AugAssign, ast.AnnAssign))
            if not is_bare and isinstance(stmt, ast.Expr):
                # Any `Expr(Constant)` is a no-op (Python's docstring pattern, e.g. a leading triple-quoted string). We
                # accept it anywhere in the body rather than only at position 0 because the kernel-coverage AST
                # transformer (see `_kernel_coverage.py`) prepends a `_qd_cov[...] = 1` probe under
                # `QD_KERNEL_COVERAGE=1`, which would otherwise push the docstring to position 1 and have us flag it as
                # a bare top-level statement.
                is_constant_expr = isinstance(stmt.value, ast.Constant)
                is_bare = not is_constant_expr
            if not is_bare:
                continue
            if CheckpointTransformer._is_coverage_probe_assign(stmt):
                continue
            stmt_kind = type(stmt).__name__
            raise QuadrantsSyntaxError(
                f"qd.checkpoint() body cannot contain a bare top-level {stmt_kind} statement "
                f"(line {getattr(stmt, 'lineno', '?')}): every top-level statement in a checkpoint must be inside a "
                f"for-loop (or other control-flow construct), so the compiler can lower it as its own offloaded task "
                f"with the correct cp_id. Wrap the statement in `for _ in range(1):` to keep the original intent:\n"
                f"\n"
                f"    with qd.checkpoint(cp_id, yield_on=flag):\n"
                f"        for _ in range(1):\n"
                f"            <your statement here>\n"
                f"        for i in range(arr.shape[0]):\n"
                f"            ...\n"
            )

        kernel.checkpoint_yield_on_args.append(yield_on_label)
        kernel.checkpoint_yield_on_cpp_arg_ids.append(yield_on_cpp_arg_id)
        kernel.checkpoint_user_labels_by_cp_id.append(info.cp_id)
        # Hand control to the C++ ASTBuilder so that every for-loop emitted by `build_stmts` below is tagged with this
        # checkpoint's internal `cp_id` on its `ForLoopConfig.checkpoint_id`. The C++ counter is the source of truth for
        # the dense internal cp_id; we cross-check it against the Python list index so that a future refactor that
        # misaligns the two surfaces fires immediately.
        cpp_cp_id = ctx.ast_builder.begin_checkpoint()
        py_cp_id = len(kernel.checkpoint_yield_on_args) - 1
        assert cpp_cp_id == py_cp_id, (
            f"C++ ASTBuilder.begin_checkpoint() returned cp_id={cpp_cp_id} but Python "
            f"kernel.checkpoint_yield_on_args index expected {py_cp_id}; these counters "
            f"must stay in lockstep so the GraphManager can index yield_on by cp_id"
        )
        ctx._in_checkpoint = True
        try:
            build_stmts(ctx, node.body)
        finally:
            ctx._in_checkpoint = False
            ctx.ast_builder.end_checkpoint()
        return None

    @staticmethod
    def _make_implicit_checkpoint_with(for_stmt: ast.For) -> ast.With:
        """Construct a synthetic ``with qd.checkpoint(): <for_stmt>`` AST node carrying the `_qd_implicit` marker.

        The `qd` name resolves via the kernel's module globals at AST-walk time; in practice every kernel that imports
        `quadrants as qd` (the canonical pattern) has it available. If the user imported as `import quadrants as t`,
        `with qd.checkpoint(...)` would already fail to resolve, so we don't worry about that case here.
        """
        call = ast.Call(
            func=ast.Attribute(value=ast.Name(id="qd", ctx=ast.Load()), attr="checkpoint", ctx=ast.Load()),
            args=[],
            keywords=[],
        )
        setattr(call, _IMPLICIT_MARKER_ATTR, True)
        with_stmt = ast.With(
            items=[ast.withitem(context_expr=call, optional_vars=None)],
            body=[for_stmt],
            type_comment=None,
        )
        ast.copy_location(with_stmt, for_stmt)
        ast.copy_location(call, for_stmt)
        ast.copy_location(call.func, for_stmt)
        ast.copy_location(call.func.value, for_stmt)
        # ast.With requires a complete locations table for downstream passes; fix up missing fields.
        ast.fix_missing_locations(with_stmt)
        return with_stmt

    @staticmethod
    def auto_wrap_for_loops(stmts: list[ast.stmt]) -> list[ast.stmt]:
        """Auto-wrap pass for `@qd.kernel(graph=True, checkpoints=True)` kernels.

        Walks *stmts* and returns a new list where every `ast.For` not already inside a `with qd.checkpoint(...)` block
        is wrapped in a synthetic implicit checkpoint. Recurses into `while qd.graph_do_while(...)` bodies so for-loops
        nested in the WHILE body get the same treatment. Other compound statements (`ast.If`, `ast.With`,
        non-graph_do_while `ast.While`, `ast.Try`) are passed through unchanged -- they're not the common pattern in
        Quadrants kernel bodies and recursing into them risks wrapping nested for-loops that the user intended to be
        sub-tasks of a larger control-flow block. Bare top-level statements (assignments, expressions, coverage probes)
        are also passed through unchanged so they remain in the kernel prologue with `cp_id=-1` and run on every launch.
        """
        new_stmts: list[ast.stmt] = []
        for stmt in stmts:
            if isinstance(stmt, ast.For):
                new_stmts.append(CheckpointTransformer._make_implicit_checkpoint_with(stmt))
            elif CheckpointTransformer.is_explicit_checkpoint_with(stmt):
                # User has already wrapped this for-loop (or block of for-loops) -- leave alone.
                new_stmts.append(stmt)
            elif isinstance(stmt, ast.While):
                # `while qd.graph_do_while(...):` -- recurse into the loop body. (Plain `while <cond>:` is not a
                # supported Quadrants kernel construct; the `build_While` transformer will reject it later, so we don't
                # special-case it here.)
                stmt.body = CheckpointTransformer.auto_wrap_for_loops(stmt.body)
                new_stmts.append(stmt)
            else:
                new_stmts.append(stmt)
        return new_stmts
